### ISSUE TITLE
Missing challenge question n 1 comment

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad22-practical-3---event-handling-NP-Lim-Hong-Ying#2]
https://github.com/MAD11877/mad22-practical-3---event-handling-NP-Lim-Hong-Ying/blob/1aeb9f0b60f4f8d377db7142545de5d54706c46c/app/src/main/java/sg/edu/np/practical3/ListActivity.java#L36

what's with the zero?

**Comment by Lim-Hong-Ying** [comment]
Removed extra 0 and done challenge question
